### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by Hakler123** [cheaTech/TrovoViewbot#24]
kako ovo uopste da aktiviram bro kad nece cmd onaj nit ista imas li disc il insta il ovdje objkasni

**Comment by IgrutinovicL** [comment]
Preporucujem ti da naucis python ako ces da koristis ovog bota jer nije namenjen za one koji ne programiraju. Mnogo bih morao da objasnjavam i opet uzalud bi bilo. [Link za python](https://www.learnpython.org/)

**Comment by Hakler123** [comment]
Dobro brate de mi bar reci jel cita sate ja kupio 20 proksija privatnih i kurac ne cita sate nista ako mozes kako pomoc brate javi i napisi svoj insta

**Comment by Hakler123** [comment]
ajde napisi insta da se cujemo privatno

**Comment by IgrutinovicL** [comment]
Za brojanje sati ti trebaju "Residential proxy" provajderi. To sve pise na mom README.md. Ovaj bot se ne isplati za pojedinacne streamer-e. On sluzi da prodajes usluge botova. Za to ti trebaju ti "residential proxy" i jake veze da bi izgubio limit za bandwith.

**Comment by Hakler123** [comment]
aha drug jel to sigurno da ce brojat sate na tim proxyjama ja sma skino onaj program od onog turcina samo trebaju sad proxy al on reko da moraju bit privati a ti kazes da moraju bit residenital i ajd discord daj il insta da se cujemo platit cu ti samo da mi pomognes nesto

**Comment by IgrutinovicL** [comment]
Residential proxy je poprilicno opasan jer obicno imaju limit na GB koje mozes da koristis. A kada koristis bota taj broj ide na gore jako brzo. Tako da bi tebi trebalo i vise od 2TB za koriscenje. To bi bila cena verovatno preko $5000...

**Comment by IgrutinovicL** [comment]
A te proxy na webshare mozes da probas, nadam se da imaju refund ako ti ne bude brojalo. Moj savet je da ne experimentises. A instagram ne koristim kao ni discord.

**Comment by Hakler123** [comment]
na webshare ima opcija za limit tj da ukinem limit izadje skuplje za 20  dolara  al vredi al pitam te jesil siguran da ce brojat sate residental proxy nego privatni proxy

**Comment by Hakler123** [comment]
ja samo ne znam kako ovi rade npr ubace 80 botova i sve i jednog bota mu ocita tj.sate ocita kako sta rade Bog zna

**Comment by Hakler123** [comment]
i to ne pisu po chatu al opet racuna sate i taj na githubu sto je napravio program strimer bot on kaze da moraju bit privatne veeze tj proxy

**Comment by Hakler123** [comment]
jel i ovi sto botuju koriste te proxye il
